### ISSUE TITLE
Ensure "spring-cloud-services-config-client" JAR is excluded from the generated Apps

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/rabbit#8]
Required by #6 
Relates to #5

**Comment by sobychacko** [comment]
The explicit inclusion of `app-starters-micrometer-common` in the generated apps through global dependency in the plugin configuration will bring the connector jars back to the generated apps. In order to fix this, we need to do the following.
1. Re-declare the `additionalGlobalDepencny` in the rabbit source/sink plugin configuration and override it by excluding the `app-starters-micrometer-common` dependency.
2. Then explicitly add `app-starters-micrometer-common` to the rabbit source and sink pom as a dependency so that the generated app will see this as a transitive dependency. This way, maven will not bring any inherited dependencies for `app-starters-micrometer-common` from the parent into the generated apps.

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud-stream-app-starters/rabbit/commit/6338c1e69c988633217d7643ef32f27ed884ca52.
